# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Optiapps - Multi TikTok Pixels"
client_id = "3b6c6aadd89f02bd1325039a385735ea"
application_url = "https://tiktok.optiapps.xyz"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://tiktok.optiapps.xyz/authenticate" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
